"""
Django settings for telsuko project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+$t&-vus6&zb-h8#d@$9hhorw5(!k0n%709*nd2_x^y3wc18#1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'information',
      'django.contrib.sites',   # <--
    # <--
 'allauth.account',   # <--
 'allauth.socialaccount',   # <--
 'allauth.socialaccount.providers.google',
  'allauth.socialaccount.providers.github',  
  'allauth.socialaccount.providers.facebook',   # <--
     # <-- Here social-auth-app-django
]

THIRD_PARTY_APPS=[
    'crispy_forms',
     'social_app',   # <--
]
LOCAL_APPS=[
    'information',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'social_django.middleware.SocialAuthExceptionMiddleware',  # <-- Here
]

ROOT_URLCONF = 'telsuko.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #'social_django.context_processors.backends',  # <-- Here
                #'social_django.context_processors.login_redirect', # <-- Here
            ],
        },
    },
]

# settings.py

#[...]

# add this code

WSGI_APPLICATION = 'telsuko.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'vasu',
        'USER':'root',
        'PASSWORD':'Darlin@#',
        'HOST':'localhost',
        'PORT':'3306',
        'OPTIONS':{
          'init_command':"SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


STATIC_URL = '/static/'
MEDIA_URL='/images/'

STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')
]
STATIC_ROOT=os.path.join(BASE_DIR,'assets')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SITE_ID = 1


LOGIN_REDIRECT_URL='dashboard'
#LOGIN_URL = 'login'
#LOGOUT_URL = 'logout'
#LOGIN_REDIRECT_URL = 'home'


#EMAIL_BACKEND='django.core.mail.backends.xonsole.EmailBackend'

EMAIL_HOST= 'smtp.gmail.com'
EMAIL_PORT='587'
EMAIL_HOST_USER='srinivasgirijala899@gmail.com'
EMAIL_HOST_PASSWORD='vtakjcizgnahuhwb'
EMAIL_USE_TLS=True

AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',

)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'METHOD': 'oauth2',
        #'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name'
        ],
        'EXCHANGE_TOKEN': True,
        #'LOCALE_FUNC': 'path.to.callable',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v7.0',
    }
}



RECAPTCHA_PUBLIC_KEY = '6Ldwd38bAAAAAJ5FZs3vkl_ynjXt58kvyMA-T96B'
RECAPTCHA_PRIVATE_KEY = '6Ldwd38bAAAAAICOAOzU2nhuKV-dXjaFL6QMSFkK'


##SOCIAL_AUTH_FACEBOOK_KEY='532090481438163'
###SOCIAL_AUTH_FACEBOOK_SECRET='6fa373188b1967b2cfaa6344354f5447'

#SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY='86l2wx293am24p'
#SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET='zFpb4uKkcCngGw4V'

#SOCIAL_AUTH_GITHUB_KEY='06741e40f141f4aa8f46'
##SOCIAL_AUTH_GITHUB_SECRET='5322b49e898706c23266f48ede66e836a55fcadf'


#SOCIAL_AUTH_GOOGLE_KEY='430269771665-kli4c0vfl3ncr056lgqd8od5faag178f.apps.googleusercontent.com'
#SOCIAL_AUTH_GOOGLE_SECRET='32hOjNqKs5AN7Vr67TLuEQ4O'