# Generated by Django 3.1.7 on 2021-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20210715_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
