# Generated by Django 3.1.7 on 2021-07-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='customers',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='username',
        ),
        migrations.AddField(
            model_name='subscribers',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
